### ISSUE TITLE
Do not import the complete google/cloud

### ISSUE THREAD

**Issue by gogl92** [inquid/yii2-google-debugger#1]
Use this instead https://github.com/googleapis/google-cloud-php-logging

**Comment by micaelomota** [comment]
@gogl92 it uses that internally. This library is just a wrapper of google logger client for Yii2

**Comment by gogl92** [comment]
> @gogl92 it uses that internally. This library is just a wrapper of google logger client for Yii2

I know I'm the author of this library, in the beginning it was using the whole Google cloud package instead of the only dependency it needed, I fixed it in this commit so we can actually close this ticket. 

https://github.com/inquid/yii2-google-debugger/commit/41752cd97c755e9f9c23a1b49e7415bae6408a9b

**Comment by micaelomota** [comment]
LOL @gogl92 thanks anyway, this library saved me some time <3
